# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LinaWolf\FormDoubleOptIn\:
    resource: '../Classes/*'

  # EventListeners
  LinaWolf\FormDoubleOptIn\Compatibility\SlotReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onOptInRecordCreated'
        event: LinaWolf\FormDoubleOptIn\Event\AfterOptInCreationEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onOptInRecordValidated'
        event: LinaWolf\FormDoubleOptIn\Event\AfterOptInValidationEvent
